name: AABBuilder

on:
  push:
    branches:
      - main
    paths:
      - aab_counter.txt

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'  # Use your desired Flutter version

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          **/flutter/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Clean Build Cache
      run: flutter clean

    - name: Build AAB
      run: flutter build appbundle --verbose

    - name: FTP Transfer
      uses: joutvhu/ftp-transfer@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 21
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        commands: |
          put ./build/app/outputs/bundle/release/app-release.aab ./
